Update kubectl_trigger_cronjob function to wait for job's Pod (BACK-708)

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -460,10 +460,18 @@ kubectl_trigger_cronjob() {
   job_name=$(echo "${job_name}-${job_name_suffix}" | tr '[:upper:]' '[:lower:]' | cut -c1-63)
 
   kubectl --namespace $namespace create job --from=cronjob/$from_cronjob $job_name
+  # Capture the exit status
+  EXIT_STATUS=$?
 
-  # if [ "$show_log" = true ]; then
-  #   kubectl logs --namespace $namespace --all-containers=true --follow job/$job_name
-  # fi
+  if [ "$show_log" = true ]; then
+    echo "Wait for job's Pod to be Ready before showing logs"
+    kubectl wait --timeout 90s --for=condition=Ready --namespace $namespace pod -l job-name=$job_name
+    EXIT_STATUS=$?
+    kubectl logs --namespace $namespace --all-containers=true --follow job/$job_name
+  fi
+
+  # Exit with the status of the create job or wait for logs
+  exit $EXIT_STATUS
 }
 
 # support private registry
